#!/usr/bin/env bash
set -eu

function defer() {
	local fn=${1}
	local traps=$(trap -p EXIT | sed -En "s/trap -- '([^']*)' EXIT/\1/p")
	local sep=$([[ -z ${traps} ]] || echo ';')
	trap -- "${traps}${sep}${fn}" EXIT
}

function strap_brew() {
	if [[ ! -f /usr/local/bin/brew ]]; then
		local install_sh=$(mktemp)
		echo ${install_sh}
		defer "rm ${install_sh}"
		curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh	-o {install_sh}
		less ${install_sh}
		bash ${install_sh}
	fi
}

function strap_ansible() {
	brew install ansible
	ansible-playbook ./brewtstrap.yml 
}

strap_brew
strap_ansible
